github: [DasHund007]
patreon: # Leave empty if not using Patreon
open_collective: # Leave empty if not using Open Collective
ko_fi: # Leave empty if not using Ko-fi
tidelift: # Leave empty if not using Tidelift
community_bridge: # Leave empty if not using Community Bridge
liberapay: # Leave empty if not using Liberapay
issuehunt: # Leave empty if not using IssueHunt
lfx_crowdfunding: # Leave empty if not using LFX Crowdfunding
polar: # Leave empty if not using Polar
buy_me_a_coffee: # Leave empty if not using Buy Me a Coffee
thanks_dev: # Leave empty if not using thanks.dev
custom: ['https://www.paypal.com/paypalme/KenanMesserr']
